export enum UserErrorCode {
  FORBIDDEN = "FORBIDDEN",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  INVALID_OPERATION = "INVALID_OPERATION",
  CANNOT_REMOVE_SELF = "CANNOT_REMOVE_SELF",
  CROSS_TENANT_ACCESS = "CROSS_TENANT_ACCESS",
}
