export enum SchoolGqlInputNames {
  ListGradesInput = "ListGradesInput",
  ListSchoolsInput = "ListSchoolsInput",
  UpdateGradeInput = "UpdateGradeInput",
  CreateGradeInput = "CreateGradeInput",
  CreateSchoolInput = "CreateSchoolInput",
  UpdateSchoolInput = "UpdateSchoolInput",
  EnrollStudentInput = "EnrollStudentInput",
  SetAdminStatusInput = "SetAdminStatusInput",
  ListClassroomsInput = "ListClassroomsInput",
  ListSchoolCounselors = "ListSchoolCounselors",
  SetSchoolStatusInput = "SetSchoolStatusInput",
  CloseEnrollmentInput = "CloseEnrollmentInput",
  UpdateClassroomInput = "UpdateClassroomInput",
  CreateClassroomInput = "CreateClassroomInput",
  ListSchoolAdminsInput = "ListSchoolAdminsInput",
  CreateSchoolAdminInput = "CreateSchoolAdminInput",
  AssignStudentsToCounselorInput = "AssignStudentsToCounselorInput",
  ListEnrollmentsByClassroomInput = "ListEnrollmentsByClassroomInput",
  ListCounselorStudentAssignmentsInput = "ListCounselorStudentAssignmentsInput",
  RestoreCounselorStudentAssignmentInput = "RestoreCounselorStudentAssignmentInput",
  ArchiveCounselorStudentAssignmentInput = "ArchiveCounselorStudentAssignmentInput",
  ListSchoolStudentsForCounselorAssignment = "ListSchoolStudentsForCounselorAssignment",
}

export enum SchoolGqlObjectNames {
  Grade = "Grade",
  School = "School",
  Classroom = "Classroom",
  GradeList = "GradeList",
  SchoolList = "SchoolList",
  Enrollment = "Enrollment",
  SchoolAdmin = "SchoolAdmin",
  PublicSchool = "PublicSchool",
  ClassroomList = "ClassroomList",
  EnrollmentList = "EnrollmentList",
  SchoolAdminList = "SchoolAdminList",
  SchoolCounselor = "SchoolCounselor",
  PublicSchoolList = "PublicSchoolList",
  SchoolCounselorList = "SchoolCounselorList",
  CreateSchoolAdminResult = "CreateSchoolAdminResult",
  CounselorStudentAssignment = "CounselorStudentAssignment",
  CounselorStudentAssignmentList = "CounselorStudentAssignmentList",
  CounselorStudentAssignmentResult = "CounselorStudentAssignmentResult",
  SchoolStudentAssignmentCandidate = "SchoolStudentAssignmentCandidate",
  SchoolStudentAssignmentCandidateList = "SchoolStudentAssignmentCandidateList",
}

export enum SchoolGqlQueryNames {
  Grades = "grades",
  Schools = "schools",
  Classrooms = "classrooms",
  SchoolById = "schoolById",
  SchoolAdmins = "schoolAdmins",
  PublicSchools = "publicSchools",
  EnrollmentsByClassroom = "enrollmentsByClassroom",
}

export enum SchoolGqlMutationNames {
  CreateSchool = "createSchool",
  UpdateSchool = "updateSchool",
  SetAdminStatus = "setAdminStatus",
  SetSchoolStatus = "setSchoolStatus",
  CreateSchoolAdmin = "createSchoolAdmin",

  CreateGrade = "createGrade",
  UpdateGrade = "updateGrade",
  ArchiveGrade = "archiveGrade",
  RestoreGrade = "restoreGrade",

  CreateClassroom = "createClassroom",
  UpdateClassroom = "updateClassroom",
  ArchiveClassroom = "archiveClassroom",
  RestoreClassroom = "restoreClassroom",

  EnrollStudent = "enrollStudent",
  CloseEnrollment = "closeEnrollment",
}
