export enum SchoolErrorCode {
  FORBIDDEN = "FORBIDDEN",
  INVALID_NAME = "INVALID_NAME",
  ADMIN_NOT_FOUND = "ADMIN_NOT_FOUND",
  SCHOOL_NOT_FOUND = "SCHOOL_NOT_FOUND",
  SCHOOL_CODE_TAKEN = "SCHOOL_CODE_TAKEN",
  INVALID_OPERATION = "INVALID_OPERATION",
  INVALID_STUDENT_IDS = "INVALID_STUDENT_IDS",
  COUNSELOR_NOT_FOUND = "COUNSELOR_NOT_FOUND",
  NOTIFICATION_FAILED = "NOTIFICATION_FAILED",
  ADMIN_EMAIL_REQUIRED = "ADMIN_EMAIL_REQUIRED",
  COUNSELOR_ASSIGNMENT_NOT_FOUND = "COUNSELOR_ASSIGNMENT_NOT_FOUND",
}
