export enum SchoolMessage {
  CREATED = "CREATED",
  UPDATED = "UPDATED",
  ADMIN_CREATED = "ADMIN_CREATED",
  STATUS_UPDATED = "STATUS_UPDATED",
  ADMIN_STATUS_UPDATED = "ADMIN_STATUS_UPDATED",
  COUNSELOR_ASSIGNMENT_CREATED = "COUNSELOR_ASSIGNMENT_CREATED",
  COUNSELOR_ASSIGNMENT_RESTORED = "COUNSELOR_ASSIGNMENT_RESTORED",
  COUNSELOR_ASSIGNMENT_ARCHIVED = "COUNSELOR_ASSIGNMENT_ARCHIVED",
}
