export enum ParentErrorCode {
  FORBIDDEN = "PARENT_FORBIDDEN",
  CHILD_NOT_FOUND = "PARENT_CHILD_NOT_FOUND",
  RESULT_NOT_FOUND = "PARENT_RESULT_NOT_FOUND",
  SESSION_NOT_FOUND = "PARENT_SESSION_NOT_FOUND",
  INVALID_COUNSELOR = "PARENT_INVALID_COUNSELOR",
  CHILD_ACCESS_DENIED = "PARENT_CHILD_ACCESS_DENIED",
  SCHOOL_SCOPE_MISSING = "PARENT_SCHOOL_SCOPE_MISSING",
  SESSION_NOT_CANCELABLE = "PARENT_SESSION_NOT_CANCELABLE",
}
