export enum NotificationErrorCode {
  SMTP_ERROR = "SMTP_ERROR",
  PROVIDER_ERROR = "PROVIDER_ERROR",
  KAVENEGAR_ERROR = "KAVENEGAR_ERROR",
  INVALID_DESTINATION = "INVALID_DESTINATION",
  PROVIDER_NOT_CONFIGURED = "PROVIDER_NOT_CONFIGURED",
}
