export enum NotificationTemplate {
  OTP_LOGIN = "OTP_LOGIN",
  ADMIN_CREDENTIALS = "ADMIN_CREDENTIALS",
  ACCESS_REQUEST_APPROVED = "ACCESS_REQUEST_APPROVED",
  ACCESS_REQUEST_REJECTED = "ACCESS_REQUEST_REJECTED",
}
