export const MembershipCodes = {
  FORBIDDEN: "FORBIDDEN",
  UNAUTHORIZED: "UNAUTHORIZED",
  ROLE_INVALID: "ROLE_INVALID",
  SCHOOL_INACTIVE: "SCHOOL_INACTIVE",
  SCHOOL_NOT_FOUND: "SCHOOL_NOT_FOUND",
  MEMBERSHIP_EXISTS: "MEMBERSHIP_EXISTS",
  IDENTIFIER_INVALID: "IDENTIFIER_INVALID",
  IDENTIFIER_REQUIRED: "IDENTIFIER_REQUIRED",
  MEMBERSHIP_NOT_FOUND: "MEMBERSHIP_NOT_FOUND",
  ONLY_ADMIN_CAN_REVIEW: "ONLY_ADMIN_CAN_REVIEW",
  ONLY_PENDING_CAN_BE_REVIEWED: "ONLY_PENDING_CAN_BE_REVIEWED",
};

export type MembershipCode =
  (typeof MembershipCodes)[keyof typeof MembershipCodes];
