export enum StudentErrorCode {
  FORBIDDEN = "STUDENT_FORBIDDEN",
  DUPLICATE_ANSWER = "STUDENT_DUPLICATE_ANSWER",
  INVALID_COUNSELOR = "STUDENT_INVALID_COUNSELOR",
  SCHOOL_SCOPE_MISSING = "STUDENT_SCHOOL_SCOPE_MISSING",
  ASSIGNMENT_NOT_FOUND = "STUDENT_ASSIGNMENT_NOT_FOUND",
  NOTIFICATION_NOT_FOUND = "STUDENT_NOTIFICATION_NOT_FOUND",
  COMPARE_RESULT_NOT_FOUND = "STUDENT_COMPARE_RESULT_NOT_FOUND",
  ASSESSMENT_RESULT_NOT_FOUND = "STUDENT_ASSESSMENT_RESULT_NOT_FOUND",
  INVALID_ASSIGNMENT_QUESTION = "STUDENT_INVALID_ASSIGNMENT_QUESTION",
  COUNSELING_SESSION_NOT_FOUND = "STUDENT_COUNSELING_SESSION_NOT_FOUND",
  ASSIGNMENT_ALREADY_EVALUATED = "STUDENT_ASSIGNMENT_ALREADY_EVALUATED",
  COUNSELING_SESSION_NOT_CANCELABLE = "STUDENT_COUNSELING_SESSION_NOT_CANCELABLE",
}
