mutation RequestLoginOtp($input: RequestLoginOtpInput!) {
  requestLoginOtp(input: $input) {
    message
    resendAfter
  }
}

mutation VerifyLoginOtp($input: VerifyLoginOtpInput!) {
  verifyLoginOtp(input: $input) {
    accessToken
    refreshToken
    expiresIn
    me {
      id
      globalRole
      email
      phone
    }
  }
}

mutation RefreshToken($input: RefreshTokenInput!) {
  refreshToken(input: $input) {
    accessToken
    refreshToken
    expiresIn
    me {
      id
      globalRole
      email
      phone
    }
  }
}

mutation Logout($input: LogoutInput!) {
  logout(input: $input) {
    message
  }
}

mutation SignInSuperAdmin($input: SignInSuperAdminInput!) {
  signInSuperAdmin(input: $input) {
    accessToken
    refreshToken
    expiresIn
    me {
      id
      globalRole
      email
    }
  }
}

mutation RefreshSuperAdminToken($input: RefreshSuperAdminTokenInput!) {
  refreshSuperAdminToken(input: $input) {
    accessToken
    refreshToken
    expiresIn
    me {
      id
      globalRole
      email
    }
  }
}

mutation LogoutSuperAdmin($input: LogoutSuperAdminInput!) {
  logoutSuperAdmin(input: $input) {
    message
  }
}
