import { IntelligenceKey } from "@prisma/client";

export const MULTIPLE_INTELLIGENCE_QUESTIONS: Array<{
  code: number;
  text: string;
  order: number;
  intelligenceKeys: IntelligenceKey[];
}> = [
  {
    code: 1,
    text: "دوست دارم در کلاس‌های خودشناسی شرکت کنم.",
    order: 1,
    intelligenceKeys: [IntelligenceKey.INTRAPERSONAL],
  },
  {
    code: 2,
    text: "بلدم با یک ساز موسیقی کار کنم.",
    order: 2,
    intelligenceKeys: [IntelligenceKey.MUSICAL],
  },
  {
    code: 3,
    text: "وقتی ورزش می کنم فکر کردن به مسائل و حل آن‌ها برایم ساده است.",
    order: 3,
    intelligenceKeys: [IntelligenceKey.BODILY_KINESTHETIC],
  },
  {
    code: 4,
    text: "معمولاً یک بخش از یک آهنگ یا ترانه در ذهنم در حال اجرا است.",
    order: 4,
    intelligenceKeys: [IntelligenceKey.MUSICAL],
  },
  {
    code: 5,
    text: "مدیریت مالی و دخل و خرج برایم راحت است.",
    order: 5,
    intelligenceKeys: [IntelligenceKey.LOGICAL_MATHEMATICAL],
  },
  {
    code: 6,
    text: "داستان‌ سرهم کردن برایم راحت است.",
    order: 6,
    intelligenceKeys: [IntelligenceKey.LINGUISTIC],
  },
  {
    code: 7,
    text: "انرژی زیادی برای فعالیت فیزیکی و ورزش کردن دارم.",
    order: 7,
    intelligenceKeys: [IntelligenceKey.BODILY_KINESTHETIC],
  },
  {
    code: 8,
    text: "از تغییرات آب و هوایی و زیست‌محیطی مطلع هستم.",
    order: 8,
    intelligenceKeys: [IntelligenceKey.NATURALISTIC],
  },
  {
    code: 9,
    text: "از بازی‌های کلمات مثل جداول و جستجوی لغات درهم ریخته لذت می‌برم.",
    order: 9,
    intelligenceKeys: [IntelligenceKey.LINGUISTIC],
  },
  {
    code: 10,
    text: "در مدرسه از حل سوالات ریاضی لذت می‌بردم.",
    order: 10,
    intelligenceKeys: [IntelligenceKey.LOGICAL_MATHEMATICAL],
  },
  {
    code: 11,
    text: "از بازی‌های منطقی ریاضی مثل جدول سودوکو و شطرنج لذت می‌برم.",
    order: 11,
    intelligenceKeys: [IntelligenceKey.LOGICAL_MATHEMATICAL],
  },
  {
    code: 12,
    text: "ترجیح می‌دهم آخر هفته را در خانه سپری کنم، به جای اینکه به یک رویداد اجتماعی بروم.",
    order: 12,
    intelligenceKeys: [IntelligenceKey.INTERPERSONAL],
  },
  {
    code: 13,
    text: "به نظرم زندگی‌ام بدون موسیقی چیزی کم دارد.",
    order: 13,
    intelligenceKeys: [IntelligenceKey.MUSICAL],
  },
  {
    code: 14,
    text: "می‌توانم دروغ‌های قانع‌کننده‌ای بگویم.",
    order: 14,
    intelligenceKeys: [IntelligenceKey.INTERPERSONAL],
  },
  {
    code: 15,
    text: "حداقل یک ورزش یا رقص انجام می‌دهم.",
    order: 15,
    intelligenceKeys: [IntelligenceKey.BODILY_KINESTHETIC],
  },
  {
    code: 16,
    text: "تست‌های هوش و شخصیت‌شناسی برایم جذاب هستند.",
    order: 16,
    intelligenceKeys: [IntelligenceKey.INTRAPERSONAL],
  },
  {
    code: 17,
    text: "وقتی کسی حرف می‌زند یا نوشته‌ای را می‌خوانم، به کلمات به کار برده شده و غلط‌های نگارشی دقت می‌کنم.",
    order: 17,
    intelligenceKeys: [IntelligenceKey.LINGUISTIC],
  },
  {
    code: 18,
    text: "باغبانی را دوست دارم. (همیشه دوست داشتم یک باغچهٔ‌ شخصی داشته باشم.)",
    order: 18,
    intelligenceKeys: [IntelligenceKey.NATURALISTIC],
  },
  {
    code: 19,
    text: "از ابهام خوشم نمی‌آید. دوست دارم همه چیز واضح و شفاف باشد.",
    order: 19,
    intelligenceKeys: [
      IntelligenceKey.LOGICAL_MATHEMATICAL,
      IntelligenceKey.INTRAPERSONAL,
    ],
  },
  {
    code: 20,
    text: "وقتی در سفر هستم مناظر طبیعی بیش از هر چیزی توجهم را جلب می‌کنند.",
    order: 20,
    intelligenceKeys: [IntelligenceKey.NATURALISTIC],
  },
  {
    code: 21,
    text: "قدم زدن در طبیعت برایم لذت‌بخش است.",
    order: 21,
    intelligenceKeys: [IntelligenceKey.NATURALISTIC],
  },
  {
    code: 22,
    text: "از آدم‌های غیرمنطقی خوشم نمی‌آید.",
    order: 22,
    intelligenceKeys: [IntelligenceKey.LOGICAL_MATHEMATICAL],
  },
  {
    code: 23,
    text: "جذابیت یک موسیقی به حس و حالی که هنگام گوش دادن آن دارم بسیار وابسته است.",
    order: 23,
    intelligenceKeys: [IntelligenceKey.MUSICAL],
  },
  {
    code: 24,
    text: "دوست دارم قاعده‌مند و منظم باشم.",
    order: 24,
    intelligenceKeys: [IntelligenceKey.LOGICAL_MATHEMATICAL],
  },
  {
    code: 25,
    text: "از عکاسی لذت می‌برم.",
    order: 25,
    intelligenceKeys: [IntelligenceKey.VISUAL_SPATIAL],
  },
  {
    code: 26,
    text: "در بازی‌های پرتابی مثل دارت و فریزبی مهارت زیادی دارم.",
    order: 26,
    intelligenceKeys: [IntelligenceKey.BODILY_KINESTHETIC],
  },
  {
    code: 27,
    text: "از برنامه‌های تلویزیونی در مورد طبیعت (مثل راز بقا) خوشم می‌آید.",
    order: 27,
    intelligenceKeys: [IntelligenceKey.NATURALISTIC],
  },
  {
    code: 28,
    text: "ترانه‌های جدید را زود حفظ می‌کنم.",
    order: 28,
    intelligenceKeys: [IntelligenceKey.MUSICAL],
  },
  {
    code: 29,
    text: "وقتی در حال فکر کردن و تمرکز هستم شروع به خط‌خطی کردن روی کاغذ می‌کنم.",
    order: 29,
    intelligenceKeys: [
      IntelligenceKey.LINGUISTIC,
      IntelligenceKey.VISUAL_SPATIAL,
    ],
  },
  {
    code: 30,
    text: "می‌توانم دیگران را رهبری و هدایت کنم.",
    order: 30,
    intelligenceKeys: [IntelligenceKey.INTERPERSONAL],
  },
  {
    code: 31,
    text: "به خوبی می‌توانم احساسات و واکنش‌هایم را در موقعیت‌های مشخص پیش‌بینی کنم.",
    order: 31,
    intelligenceKeys: [IntelligenceKey.INTRAPERSONAL],
  },
  {
    code: 32,
    text: "محاسبات ذهنی برایم ساده است.",
    order: 32,
    intelligenceKeys: [IntelligenceKey.LOGICAL_MATHEMATICAL],
  },
  {
    code: 33,
    text: "وقتی در طبیعت هستم احساس سرزندگی می‌کنم.",
    order: 33,
    intelligenceKeys: [IntelligenceKey.NATURALISTIC],
  },
  {
    code: 34,
    text: "بدون دیدن منبع یک صدا، می‌توانم آن را تشخیص دهم.",
    order: 34,
    intelligenceKeys: [IntelligenceKey.MUSICAL],
  },
  {
    code: 35,
    text: "یکی از دروس موردعلاقه‌ام در مدرسه «ادبیات» بود.",
    order: 35,
    intelligenceKeys: [IntelligenceKey.LINGUISTIC],
  },
  {
    code: 36,
    text: "دوست دارم در مورد همهٔ جوانب مشکلات با دقت و در نظر گرفتن همهٔ پیشامدهای ممکن فکر کنم.",
    order: 36,
    intelligenceKeys: [IntelligenceKey.LOGICAL_MATHEMATICAL],
  },
  {
    code: 37,
    text: "از بحث و برنامه‌های مناظره‌ای لذت می‌برم.",
    order: 37,
    intelligenceKeys: [IntelligenceKey.LINGUISTIC],
  },
  {
    code: 38,
    text: "دوست دارم در مورد گونه‌های مختلف جانوری و انواع گیاهان بیشتر بدانم.",
    order: 38,
    intelligenceKeys: [IntelligenceKey.NATURALISTIC],
  },
  {
    code: 39,
    text: "از ورزش‌های هیجان‌انگیز و بازی‌های ترسناک شهربازی لذت می‌برم.",
    order: 39,
    intelligenceKeys: [IntelligenceKey.BODILY_KINESTHETIC],
  },
  {
    code: 40,
    text: "ورزش‌های فردی را به ورزش‌های تیمی ترجیح می‌دهم.",
    order: 40,
    intelligenceKeys: [IntelligenceKey.BODILY_KINESTHETIC],
  },
  {
    code: 41,
    text: "به احساسات اطرافیانم اهمیت می‌دهم و آن‌ها را به خوبی درک می‌کنم.",
    order: 41,
    intelligenceKeys: [IntelligenceKey.INTERPERSONAL],
  },
  {
    code: 42,
    text: "اغلب دوست دارم در حین فعالیت‌های روزمره‌ام، آهنگی در پس‌زمینه پخش شود.",
    order: 42,
    intelligenceKeys: [IntelligenceKey.MUSICAL],
  },
  {
    code: 43,
    text: "با دست هایم خوب کار می‌کنم. از ساختن چیزی با دست لذت می‌برم.",
    order: 43,
    intelligenceKeys: [IntelligenceKey.BODILY_KINESTHETIC],
  },
  {
    code: 44,
    text: "فعالیت‌هایی مثل کوهنوردی و کمپ زدن در طبیعت برایم لذت‌بخش هستند.",
    order: 44,
    intelligenceKeys: [
      IntelligenceKey.NATURALISTIC,
      IntelligenceKey.VISUAL_SPATIAL,
    ],
  },
  {
    code: 45,
    text: "من برای آینده‌ام برنامه‌ها و اهداف مشخصی را تعیین می‌کنم.",
    order: 45,
    intelligenceKeys: [IntelligenceKey.INTRAPERSONAL],
  },
  {
    code: 46,
    text: "به یاد آوردن شماره تلفن‌ها برایم راحت است.",
    order: 46,
    intelligenceKeys: [],
  },
  {
    code: 47,
    text: "من یک فرد «لمسی» هستم. (یعنی حس لامسه قوی‌تری دارید و با لمس کردن بهتر یاد می‌گیرید.)",
    order: 47,
    intelligenceKeys: [IntelligenceKey.BODILY_KINESTHETIC],
  },
  {
    code: 48,
    text: "به راحتی می‌توانم بگویم یک نفر از من خوشش آمده است یا نه.",
    order: 48,
    intelligenceKeys: [IntelligenceKey.INTERPERSONAL],
  },
  {
    code: 49,
    text: "تصور اینکه یک شیء از زاویه‌ای دیگر چگونه دیده می‌شود برایم راحت است.",
    order: 49,
    intelligenceKeys: [IntelligenceKey.VISUAL_SPATIAL],
  },
  {
    code: 50,
    text: "برای سرهم کردن وسایلی که نیاز به مونتاژ دارند، از دفترچهٔ راهنمای آن استفاده نمی‌کنم.",
    order: 50,
    intelligenceKeys: [IntelligenceKey.VISUAL_SPATIAL],
  },
  {
    code: 51,
    text: "عاشق حیوانات هستم و دوست دارم حیوان خانگی داشته باشم.",
    order: 51,
    intelligenceKeys: [IntelligenceKey.NATURALISTIC],
  },
  {
    code: 52,
    text: "مشاور خوبی هستم و دوستانم برای مشورت و حمایت عاطفی نزد من می‌آیند.",
    order: 52,
    intelligenceKeys: [IntelligenceKey.INTERPERSONAL],
  },
  {
    code: 53,
    text: "یکی از درس‌های موردعلاقه‌ام در مدرسه «هنر» بود.",
    order: 53,
    intelligenceKeys: [IntelligenceKey.VISUAL_SPATIAL],
  },
  {
    code: 54,
    text: "می‌توانم به خوبی از روی نقشه بخوانم و مسیریابی کنم.",
    order: 54,
    intelligenceKeys: [IntelligenceKey.VISUAL_SPATIAL],
  },
  {
    code: 55,
    text: "مطالعه برایم لذت‌بخش است.",
    order: 55,
    intelligenceKeys: [IntelligenceKey.LINGUISTIC],
  },
  {
    code: 56,
    text: "یک دفترچه خاطرات برای ثبت اتفاقات روزانه دارم.",
    order: 56,
    intelligenceKeys: [IntelligenceKey.LINGUISTIC],
  },
  {
    code: 57,
    text: "نسبت به نقاط ضعف و قوتم واقع‌بین هستم.",
    order: 57,
    intelligenceKeys: [IntelligenceKey.INTRAPERSONAL],
  },
  {
    code: 58,
    text: "اگر ببینم کسی غمگین است و کمکی از دستم برنیاید ناراحت می‌شوم.",
    order: 58,
    intelligenceKeys: [IntelligenceKey.INTRAPERSONAL],
  },
  {
    code: 59,
    text: "زبان بدن دیگران را به خوبی می‌شناسم.",
    order: 59,
    intelligenceKeys: [IntelligenceKey.INTERPERSONAL],
  },
  {
    code: 60,
    text: "از هوای آلوده بیزارم.",
    order: 60,
    intelligenceKeys: [IntelligenceKey.NATURALISTIC],
  },
  {
    code: 61,
    text: "همیشه نسبت به احساساتی که دارم آگاه هستم.",
    order: 61,
    intelligenceKeys: [IntelligenceKey.INTRAPERSONAL],
  },
  {
    code: 62,
    text: "ورزش‌های توپی برایم ساده و جذاب هستند.",
    order: 62,
    intelligenceKeys: [IntelligenceKey.BODILY_KINESTHETIC],
  },
  {
    code: 63,
    text: "یادگیری اصول یک زبان جدید برایم ساده است.",
    order: 63,
    intelligenceKeys: [IntelligenceKey.LINGUISTIC],
  },
  {
    code: 64,
    text: "یادآوری ضرب‌المثل‌ها و نقل‌ قول‌ها برایم ساده است.",
    order: 64,
    intelligenceKeys: [IntelligenceKey.LINGUISTIC],
  },
  {
    code: 65,
    text: "سبک‌های متنوعی از موسیقی را دنبال می‌کنم.",
    order: 65,
    intelligenceKeys: [IntelligenceKey.MUSICAL],
  },
  {
    code: 66,
    text: "صحبت کردن با آدم‌های جدید برایم راحت است.",
    order: 66,
    intelligenceKeys: [IntelligenceKey.INTERPERSONAL],
  },
  {
    code: 67,
    text: "برای یادگیری یک کار جدید، تنها کافی است دست به کار شوم و خودم آن را انجام دهم.",
    order: 67,
    intelligenceKeys: [IntelligenceKey.BODILY_KINESTHETIC],
  },
  {
    code: 68,
    text: "وقتی چشم‌هایم را می‌بندم تصاویر واضحی را می‌بینم.",
    order: 68,
    intelligenceKeys: [IntelligenceKey.VISUAL_SPATIAL],
  },
  {
    code: 69,
    text: "هنگام شمارش از انگشت‌هایم کمک نمی‌گیرم.",
    order: 69,
    intelligenceKeys: [IntelligenceKey.LOGICAL_MATHEMATICAL],
  },
  {
    code: 70,
    text: "معمولاً با خودم صحبت می‌کنم. (بلند یا در ذهنم)",
    order: 70,
    intelligenceKeys: [IntelligenceKey.LINGUISTIC],
  },
  {
    code: 71,
    text: "می‌توانم مکان‌هایی را که قبلاً بوده‌ام شناسایی کنم. (حتی اگر وقتی به آنجا رفته‌ام سن کمی داشته‌ام.)",
    order: 71,
    intelligenceKeys: [IntelligenceKey.VISUAL_SPATIAL],
  },
  {
    code: 72,
    text: "در میانجی‌گری و حل مسائل بین افراد خوب هستم.",
    order: 72,
    intelligenceKeys: [IntelligenceKey.INTERPERSONAL],
  },
  {
    code: 73,
    text: "همیشه رویای خواننده یا نوازنده شدن را در سر داشته‌ام.",
    order: 73,
    intelligenceKeys: [IntelligenceKey.MUSICAL],
  },
  {
    code: 74,
    text: "ورزش‌های تیمی مثل والیبال را ترجیح می‌دهم.",
    order: 74,
    intelligenceKeys: [IntelligenceKey.BODILY_KINESTHETIC],
  },
  {
    code: 75,
    text: "خوانندگی باعث می‌شود احساس خوشحالی کنم.",
    order: 75,
    intelligenceKeys: [IntelligenceKey.MUSICAL],
  },
  {
    code: 76,
    text: "وقتی تنهایی به جای جدیدی می‌روم گم نمی‌شوم.",
    order: 76,
    intelligenceKeys: [IntelligenceKey.VISUAL_SPATIAL],
  },
  {
    code: 77,
    text: "وقتی می‌خواهم کار با وسیلهٔ جدیدی را یاد بگیرم، دوست دارم تصاویری را از نحوهٔ کار آن ببینم.",
    order: 77,
    intelligenceKeys: [IntelligenceKey.VISUAL_SPATIAL],
  },
  {
    code: 78,
    text: "تنهایی و گذراندن وقت با خودم را دوست دارم.",
    order: 78,
    intelligenceKeys: [IntelligenceKey.INTRAPERSONAL],
  },
  {
    code: 79,
    text: "من فردی اجتماعی هستم و از بودن با آدم ها لذت می‌برم.",
    order: 79,
    intelligenceKeys: [IntelligenceKey.INTERPERSONAL],
  },
  {
    code: 80,
    text: "درک نمودارها و تصاویر آموزشی برایم ساده است.",
    order: 80,
    intelligenceKeys: [IntelligenceKey.VISUAL_SPATIAL],
  },
];
