fragment AuthTokens on AuthPayload {
  expiresIn
  accessToken
  refreshToken
}

fragment UserMeBase on User {
  id
  email
  phone
  isActive
  globalRole
}

fragment MeLogin on Me {
  id
  email
  phone
  schoolId
  globalRole
  schoolRole
}

mutation Auth_SignInSuperAdmin($input: SignInSuperAdminInput!) {
  signInSuperAdmin(input: $input) {
    ...AuthTokens
    me {
      id
      email
      globalRole
    }
  }
}

mutation Auth_LogoutSuperAdmin($input: LogoutSuperAdminInput!) {
  logoutSuperAdmin(input: $input) {
    message
  }
}

mutation Auth_RequestLoginOtp($input: RequestLoginOtpInput!) {
  requestLoginOtp(input: $input) {
    message
    resendAfter
  }
}

mutation Auth_VerifyLoginOtp($input: VerifyLoginOtpInput!) {
  verifyLoginOtp(input: $input) {
    ...AuthTokens
    me {
      ...MeLogin
    }
  }
}

mutation Auth_Logout($input: LogoutInput!) {
  logout(input: $input) {
    message
  }
}

query Auth_Me {
  me {
    ...UserMeBase
  }
}

mutation Auth_RefreshSuperAdminToken($input: RefreshSuperAdminInput!) {
  refreshSuperAdminToken(input: $input) {
    ...AuthTokens
  }
}

mutation Auth_RefreshToken($input: RefreshTokenInput!) {
  refreshToken(input: $input) {
    ...AuthTokens
  }
}
