mutation RequestLoginOtp($input: RequestLoginOtpInput!) {
  requestLoginOtp(input: $input) {
    message
    resendAfter
  }
}

mutation VerifyLoginOtp($input: VerifyLoginOtpInput!) {
  verifyLoginOtp(input: $input) {
    expiresIn
    me {
      id
      schoolId
      schoolRole
      globalRole
      email
      phone
    }
  }
}

mutation RefreshToken($input: RefreshTokenInput!) {
  refreshToken(input: $input) {
    expiresIn
    me {
      id
      globalRole
      email
      phone
    }
  }
}

mutation RefreshSuperAdminToken($input: RefreshSuperAdminInput!) {
  refreshSuperAdminToken(input: $input) {
    expiresIn
    me {
      id
      globalRole
      email
    }
  }
}

mutation Logout($input: LogoutInput!) {
  logout(input: $input) {
    message
  }
}

mutation LogoutSuperAdmin($input: LogoutSuperAdminInput!) {
  logoutSuperAdmin(input: $input) {
    message
  }
}

query Me {
  me {
    id
    globalRole
    email
    phone
    isActive
  }
}
