fragment MembershipRequestItem on MembershipRequest {
  id
  grade
  email
  phone
  userId
  status
  schoolId
  lastName
  createdAt
  firstName
  nationalId
  reviewedAt
  reviewNote
  reviewedById
  requestedRole
}

fragment MembershipUser on User {
  id
  email
  phone
  isActive
  globalRole
}

fragment MyMembershipItem on Membership {
  id
  grade
  status
  schoolId
  lastName
  createdAt
  firstName
  reviewedAt
  nationalId
  approvedRole
  reviewedById
  requestedRole
  user {
    ...MembershipUser
  }
}

mutation Membership_RegisterRequest($input: RegisterRequestInput!) {
  registerRequest(input: $input) {
    id
    status
    schoolId
    approvedRole
    requestedRole
    user {
      id
      email
      phone
    }
  }
}

query Membership_ListRequests($input: ListMembershipRequestsInput!) {
  membershipRequests(input: $input) {
    total
    items {
      ...MembershipRequestItem
    }
  }
}

mutation Membership_Review($input: ReviewMembershipInput!) {
  reviewMembership(input: $input) {
    message
    membership {
      id
      email
      phone
      grade
      userId
      status
      schoolId
      lastName
      createdAt
      firstName
      reviewedAt
      nationalId
      reviewNote
      reviewedById
      requestedRole
    }
  }
}

query Membership_MyMemberships($input: MyMembershipsInput!) {
  myMemberships(input: $input) {
    ...MyMembershipItem
  }
}
