mutation AssignSchoolAdmin($input: AssignSchoolAdminInput!) {
  assignSchoolAdmin(input: $input) {
    message
    admin {
      membershipId
      schoolId
      userId
      email
      phone
      role
      status
      reviewedById
      reviewedAt
      createdAt
    }
  }
}

query MembershipRequests($input: ListMembershipRequestsInput!) {
  membershipRequests(input: $input) {
    total
    items {
      id
      userId
      schoolId
      role
      status
      firstName
      lastName
      nationalId
      grade
      email
      phone
      createdAt
    }
  }
}

mutation ReviewMembership($input: ReviewMembershipInput!) {
  reviewMembership(input: $input) {
    message
    membership {
      id
      schoolId
      userId
      role
      status
      reviewedById
      reviewedAt
      firstName
      lastName
      email
      phone
      createdAt
    }
  }
}
