fragment SchoolBase on School {
  id
  code
  name
  isActive
}

fragment SchoolFull on School {
  ...SchoolBase
  createdAt
  updatedAt
}

fragment SchoolAdminItem on SchoolAdmin {
  email
  phone
  status
  userId
  lastName
  schoolId
  firstName
  createdAt
  reviewedAt
  membershipId
  reviewedById
}

mutation School_Create($input: CreateSchoolInput!) {
  createSchool(input: $input) {
    ...SchoolFull
  }
}

query School_List($input: ListSchoolsInput!) {
  schools(input: $input) {
    total
    items {
      id
      code
      name
      isActive
      createdAt
    }
  }
}

query School_Get($input: GetSchoolInput!) {
  school(input: $input) {
    ...SchoolFull
  }
}

mutation School_UpdateStatus($input: UpdateSchoolStatusInput!) {
  updateSchoolStatus(input: $input) {
    id
    code
    name
    isActive
    updatedAt
  }
}

mutation School_AssignAdmin($input: AssignSchoolAdminInput!) {
  assignSchoolAdmin(input: $input) {
    message
    admin {
      ...SchoolAdminItem
    }
  }
}

query School_ListAdmins($input: ListSchoolAdminsInput!) {
  schoolAdmins(input: $input) {
    total
    items {
      ...SchoolAdminItem
    }
  }
}

mutation School_RemoveAdmin($input: RemoveSchoolAdminInput!) {
  removeSchoolAdmin(input: $input) {
    ...SchoolAdminItem
  }
}
