export enum AdminPasswordErrorCode {
  FORBIDDEN = "FORBIDDEN",
  WEAK_PASSWORD = "WEAK_PASSWORD",
  ADMIN_NOT_FOUND = "ADMIN_NOT_FOUND",
  TARGET_NOT_ADMIN = "TARGET_NOT_ADMIN",
  PASSWORD_NOT_SET = "PASSWORD_NOT_SET",
  NOTIFICATION_FAILED = "NOTIFICATION_FAILED",
  INVALID_CURRENT_PASSWORD = "INVALID_CURRENT_PASSWORD",
}
