export const AuthCodes = {
  OTP_INVALID: "OTP_INVALID",
  OTP_EXPIRED: "OTP_EXPIRED",
  UNAUTHORIZED: "UNAUTHORIZED",
  OTP_NOT_FOUND: "OTP_NOT_FOUND",
  OTP_RATE_LIMIT: "OTP_RATE_LIMIT",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  SCHOOL_INACTIVE: "SCHOOL_INACTIVE",
  REFRESH_INVALID: "REFRESH_INVALID",
  REFRESH_EXPIRED: "REFRESH_EXPIRED",
  OTP_ALREADY_USED: "OTP_ALREADY_USED",
  SCHOOL_NOT_FOUND: "SCHOOL_NOT_FOUND",
  ROLE_NOT_APPROVED: "ROLE_NOT_APPROVED",
  IDENTIFIER_INVALID: "IDENTIFIER_INVALID",
  OTP_RESEND_COOLDOWN: "OTP_RESEND_COOLDOWN",
  MEMBERSHIP_NOT_FOUND: "MEMBERSHIP_NOT_FOUND",
  OTP_TOO_MANY_ATTEMPTS: "OTP_TOO_MANY_ATTEMPTS",
};

export type AuthCode = (typeof AuthCodes)[keyof typeof AuthCodes];
