export enum AuthErrorCode {
  USER_DISABLED = "USER_DISABLED",
  SCHOOL_SUSPENDED = "SCHOOL_SUSPENDED",
  ACCESS_NOT_APPROVED = "ACCESS_NOT_APPROVED",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",

  OTP_EXPIRED = "OTP_EXPIRED",
  OTP_INVALID = "OTP_INVALID",
  OTP_RESEND_COOLDOWN = "OTP_RESEND_COOLDOWN",
  OTP_TOO_MANY_ATTEMPTS = "OTP_TOO_MANY_ATTEMPTS",

  AMBIGUOUS_TENANT = "AMBIGUOUS_TENANT",
  TENANT_NOT_FOUND = "TENANT_NOT_FOUND",

  REFRESH_INVALID = "REFRESH_INVALID",
  SESSION_REVOKED = "SESSION_REVOKED",
  SESSION_NOT_FOUND = "SESSION_NOT_FOUND",
}
