export enum AuthErrorCode {
  USER_DISABLED = "UserDisabled",
  OTP_SEND_FAILED = "OtpSendFailed",
  SCHOOL_SUSPENDED = "SchoolSuspended",
  ACCESS_NOT_APPROVED = "AccessNotApproved",
  INVALID_CREDENTIALS = "InvalidCredentials",

  OTP_EXPIRED = "OTP_EXPIRED",
  OTP_INVALID = "OTP_INVALID",
  OTP_RESEND_COOLDOWN = "OTP_RESEND_COOLDOWN",
  OTP_TOO_MANY_ATTEMPTS = "OTP_TOO_MANY_ATTEMPTS",

  AMBIGUOUS_TENANT = "AMBIGUOUS_TENANT",
  TENANT_NOT_FOUND = "TENANT_NOT_FOUND",

  REFRESH_INVALID = "REFRESH_INVALID",
  SESSION_REVOKED = "SESSION_REVOKED",
  SESSION_NOT_FOUND = "SESSION_NOT_FOUND",
}
