import { ReactNode } from "react";
import { Metadata } from "next";

import AppProviders from "@/providers/AppProvider";
import Header from "@layouts/Header";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className="min-h-screen antialiased bg-app text-app transition-colors"
      >
        <AppProviders>
          <Header />
          <div className="pt-16">{children}</div>
        </AppProviders>
      </body>
    </html>
  );
}
