export const SchoolAdminCodes = {
  FORBIDDEN: "FORBIDDEN",
  UNAUTHORIZED: "UNAUTHORIZED",
  SCHOOL_INACTIVE: "SCHOOL_INACTIVE",
  SCHOOL_NOT_FOUND: "SCHOOL_NOT_FOUND",
  MEMBERSHIP_NOT_FOUND: "MEMBERSHIP_NOT_FOUND",
  ONLY_PENDING_CAN_BE_REVIEWED: "ONLY_PENDING_CAN_BE_REVIEWED",
};
