export const AdminCodes = {
  FORBIDDEN: "FORBIDDEN",
  UNAUTHORIZED: "UNAUTHORIZED",
  ALREADY_ADMIN: "ALREADY_ADMIN",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  SCHOOL_INACTIVE: "SCHOOL_INACTIVE",
  SCHOOL_NOT_FOUND: "SCHOOL_NOT_FOUND",
  IDENTIFIER_INVALID: "IDENTIFIER_INVALID",
  MEMBERSHIP_NOT_FOUND: "MEMBERSHIP_NOT_FOUND",
};

export type AdminCode = (typeof AdminCodes)[keyof typeof AdminCodes];
