export enum AccessRequestErrorCode {
  FORBIDDEN = "FORBIDDEN",
  SCHOOL_NOT_FOUND = "SCHOOL_NOT_FOUND",
  SCHOOL_SUSPENDED = "SCHOOL_SUSPENDED",
  ALREADY_REVIEWED = "ALREADY_REVIEWED",
  REQUEST_NOT_FOUND = "REQUEST_NOT_FOUND",
  INVALID_DESTINATION = "INVALID_DESTINATION",
  CROSS_TENANT_ACCESS = "CROSS_TENANT_ACCESS",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  NOTIFICATION_FAILED = "NOTIFICATION_FAILED",
  DUPLICATE_PENDING_REQUEST = "DUPLICATE_PENDING_REQUEST",
}
