export enum CounselorErrorEnum {
  COUNSELOR_ONLY = "COUNSELOR_ONLY",
  REVIEW_NOT_FOUND = "COUNSELOR_REVIEW_NOT_FOUND",
  STUDENT_NOT_FOUND = "COUNSELOR_STUDENT_NOT_FOUND",
  SESSION_NOT_FOUND = "COUNSELOR_SESSION_NOT_FOUND",
  INVALID_STUDENT_IDS = "COUNSELOR_INVALID_STUDENT_IDS",
  STUDENT_NOT_ASSIGNED = "COUNSELOR_STUDENT_NOT_ASSIGNED",
  INVALID_EXPORT_FORMAT = "COUNSELOR_INVALID_EXPORT_FORMAT",
  SCHOOL_CONTEXT_REQUIRED = "COUNSELOR_SCHOOL_CONTEXT_REQUIRED",
}
