export enum CounselorGqlObjectNames {
  COUNSELOR_SESSION = "CounselorSession",
  COUNSELOR_STUDENT_CARD = "CounselorStudentCard",
  COUNSELOR_STUDENT_LIST = "CounselorStudentList",
  COUNSELOR_SESSION_LIST = "CounselorSessionList",
  COUNSELOR_NOTIFICATION = "CounselorNotification",
  COUNSELOR_EXPORT_RESULT = "CounselorExportResult",
  COMPARE_STUDENT_RESULTS = "CompareStudentResults",
  COUNSELOR_REVIEW_DETAIL = "CounselorReviewDetail",
  COUNSELOR_REVIEW_RESULT = "CounselorReviewResult",
  COUNSELOR_PROGRESS_POINT = "CounselorProgressPoint",
  COUNSELOR_STUDENT_DETAIL = "CounselorStudentDetail",
  COUNSELOR_ASSIGNMENT_ITEM = "CounselorAssignmentItem",
  COUNSELOR_ASSIGNMENT_LIST = "CounselorAssignmentList",
  COMPARE_STUDENT_RESULT_ITEM = "CompareStudentResultItem",
  COUNSELOR_NOTIFICATION_LIST = "CounselorNotificationList",
  COUNSELOR_DASHBOARD_SUMMARY = "CounselorDashboardSummary",
  COUNSELOR_ASSESSMENT_QUEUE_ITEM = "CounselorAssessmentQueueItem",
  COUNSELOR_ASSESSMENT_QUEUE_LIST = "CounselorAssessmentQueueList",
}

export enum CounselorGqlInputNames {
  MY_STUDENTS = "MyStudentsInput",
  COUNSELOR_PAGINATION = "CounselorPaginationInput",
  MY_COUNSELOR_SESSIONS = "MyCounselorSessionsInput",
  COUNSELOR_ASSIGNMENTS = "CounselorAssignmentsInput",
  COMPARE_STUDENT_RESULTS = "CompareStudentResultsInput",
  STUDENT_ASSESSMENT_QUEUE = "StudentAssessmentQueueInput",
  STUDENT_PROGRESS_TIMELINE = "StudentProgressTimelineInput",
  REVIEW_STUDENT_ASSESSMENT = "ReviewStudentAssessmentInput",
  MY_COUNSELOR_NOTIFICATIONS = "MyCounselorNotificationsInput",
  SCHEDULE_COUNSELOR_SESSION = "ScheduleCounselorSessionInput",
  EXPORT_COUNSELOR_STUDENT_REPORT = "ExportCounselorStudentReportInput",
  MARK_COUNSELOR_NOTIFICATION_READ = "MarkCounselorNotificationReadInput",
}
